name: Merge sample metadata

on:
  workflow_dispatch:
  push:
    branches:
      # When someone push to `main` branch
      - main
    paths:
      - 'samples/**/assets/sample.json'

jobs:
  build:
    name: 'Merge all sample.json files to samples.json'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
      - name: Join samples  
        run: |
          jq -s '[.[][]]' samples/**/assets/sample.json > .metadata/samples.json
      - name: Commit samples.json to main
        uses: EndBug/add-and-commit@v9
        with:
          add: '.metadata/samples.json --force'
          push: true
          token: ${{ secrets.GITHUB_TOKEN }}
